#
# loader.conf
# (/efi/loader/loader.conf)
# console-mode 2 may be needed for some hi res displays (rather than auto)
# My stable kernel package is linux-stable - adjust as needed.
# *-stable* catches legacy and new kernel-install entries
# *-stable-* catches new kernel-install auto entries only
#
default *-stable*
timeout 5
editor  yes
console-mode auto
#console-mode 2

