#!/bin/bash
#
# ./do-install <destdir>
# called from PKGBUILD
#
dest="$1"
if [ -z "${dest}" ] ; then
    echo "Missing dest dir"
    exit 1
fi

dest=$(/usr/bin/realpath "$dest")

#
# Installing
#
./src/do-install-common "$dest"
./src/do-install-binary "$dest"
./src/do-install-bash "$dest"

#
# Set default alternative
#
unset SDB_DEV_TEST
build="src/c-code/build/none"
LD_PRELOAD="" LD_LIBRARY_PATH="$build" "$build"/sd-boot-set-alternative binary "$dest"

