// SPDX-License-Identifier: GPL-2.0-or-later
// SPDX-FileCopyrightText: © 2026-present Gene C <arch@sapience.com>
/**
 *
 * Install or remove kernel using kernel-install.
 *
 *
 * /usr/lib/module/<kern-vers>/ ==> "$boot_root"/<machine-id>/
 * initrd is generated by kernel-install.
 *
 * See man kernel-install for "boot_root"
 */
#include <stdbool.h>

#include "sd-boot.h"


/**
  * inspect one kernel package
  */
int kernel_inspect(SdBoot *conf, Array_str *pkgs_arr, KernelInfo *info) {
    int ret = 0;
    char **envp = nullptr;
    Array_str env = {};

    if (info->vers == nullptr || info->vers[0] == '\0') {
        msg(MSG_ERR, "  ! sd-boot: kernel update failed to get kernel version\n");
        ret = 1;
        goto exit;
    }

    msg(MSG_NORMAL, "⦁ sd-boot: inspecting (%s) kernel package : %s %s\n", conf->oper_str, info->package, info->vers);

    if (!is_kernel_sd_boot_managed(pkgs_arr, info)) {
        msg(MSG_NORMAL, "  not managed by sd-boot - skipping %s\n", info->package);
        goto exit;
    }

    /*
     * inspect the (current) version
     */
    const char *cmd_args_arr[] = {"inspect", info->vers, info->image, nullptr};
    char **cmd_args = (char **)cmd_args_arr;

    /*
     * env provided by us:
     *  PATH
     *  KERNEL_INSTALL_PLUGINS (empty if not testing)
     *  (Note: BOOT_ROOT is handled in kernel_install_run).
     */
    ret = ki_kernel_update_env(conf, &env);
    if (ret != 0) {
        return ret;
    }
    envp = env.rows;

    ret = kernel_install_run(conf, cmd_args, envp);
    if (ret != 0) {
        msg(MSG_ERR, "  ! sd-boot: error inspecting kernel\n");
        ret = 1;
        goto exit;
    }
    msg(MSG_NORMAL, "  ↳ sd-boot: Completed kernel inspect %s\n", info->package);

exit:
    array_str_free(&env);
    return ret;
}

