// SPDX-License-Identifier: GPL-2.0-or-later
// SPDX-FileCopyrightText: © 2026-present Gene C <arch@sapience.com>
/**
 *
 * Install or remove kernel using kernel-install.
 *
 *
 * /usr/lib/module/<kern-vers>/ ==> "$boot_root"/<machine-id>/
 * initrd is generated by kernel-install.
 *
 * See man kernel-install for "boot_root"
 */
#include <linux/limits.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "sd-boot-config.h"
#include "sd-boot-kernel.h"
#include "sd-boot-msg.h"
#include "sd-boot-package.h"
#include "sd-boot-utils.h"
#include "sd-boot.h"

/*
 * Check if kernel vers exists by checking /usr/lib/modules/<vers>/vmlinuz
 * Informational only so don't fail.
 */
static bool does_kernel_version_exist(const char *kernel_version) {
    char path[PATH_MAX] = {};

    if (snprintf(path, PATH_MAX, "/usr/lib/modules/%s/vmlinuz", kernel_version) < 0) {
        return false;
    }

    if (access(path, F_OK) == 0) {
        return true;
    }

    return false;
}


/*
 * remove prev version 
 * - skip on update where prev = curr
 * - version string is = "<package>-<prev>"
 *   i.e. augment version string with package name
 * - an alpm remove hook may have been run. 
 *   check if the kernel image exists and display message.
 *   Still call kernel-install remove in case it has any housekeeping
 *   or other tasks to do.
 */
static int remove_prev_version(SdBoot *conf, char *prev, char *curr) {
    int ret = 0;
    Array_str arg_arr = {};

    if (conf->oper != KI_ADD || prev[0] == '\0' || strcmp(curr, prev) == 0) {
        return 0;
    }

    msg(MSG_NORMAL, "  ↳ sd-boot: removing prev version %s\n", prev);

    if (!does_kernel_version_exist(prev)) {
        msg(MSG_NORMAL, "           : prev version already removed\n");
    }

    ret = array_str_new(2, &arg_arr);
    if (ret != 0) {
        goto exit;
    }
    arg_arr.rows[0] = strdup("remove");
    arg_arr.rows[1] = strdup(prev);

    if (!arg_arr.rows[0] || !arg_arr.rows[1]) {
        ret = -1;
        goto exit;
    }
    array_str_refresh_row_len(&arg_arr);

    ret = kernel_install_run(conf, &arg_arr, &conf->env_active_plugins);
    if (ret != 0) {
        msg(MSG_ERR, "  ! sd-boot: error removing prev kernel %s\n", prev);
        ret = 1;
        goto exit;
    }
exit:
    array_str_free(&arg_arr);
    return ret;
}


/*
 * Prep args and env.
 * For add we use env_plugins already initialized.
 * For remove we use empty env.
 */
static int init_arg_env(SdBoot *conf, KernelInfo *info, Array_str *arg_arr, Array_str **env_arr_p) {

    int ret = 0;

    switch (conf->oper) {
        case KI_REMOVE:

            ret = array_str_new(2, arg_arr);
            if (ret != 0) {
                goto exit;
            }

            arg_arr->rows[0] = strdup("remove");
            arg_arr->rows[1] = strdup(info->vers);

            if (!arg_arr->rows[0] || !arg_arr->rows[1]) {
                ret = -1;
                goto exit;
            }
            break;

        case KI_ADD:

            ret = array_str_new(3, arg_arr);
            if (ret != 0) {
                goto exit;
            }

            arg_arr->rows[0] = strdup("add");
            arg_arr->rows[1] = strdup(info->vers);
            arg_arr->rows[2] = strdup(info->image);

            if (!arg_arr->rows[0] || !arg_arr->rows[1] || !arg_arr->rows[2]) {
                ret = -1;
                goto exit;
            }
            break;

        default:
            goto exit;
    }

    array_str_refresh_row_len(arg_arr);

    /*
     * Env is list of active plugins
     */
    *env_arr_p = &conf->env_active_plugins;

exit:
    return ret;
}

/**
  * Update one kernel package
  * - oper ~ add or remove
  */
int kernel_add_remove(SdBoot *conf, Array_str *pkgs_arr, KernelInfo *info) {
    int ret = 0;
    char *curr = nullptr;
    char *prev = nullptr;
    PackageVersion pkg_vers = {};
    Array_str arg_arr = {};
    Array_str *env_ptr = nullptr;

    if (!info->vers || info->vers[0] == '\0') {
        msg(MSG_ERR, "  ! sd-boot: kernel update failed to get kernel version\n");
        ret = 1;
        goto exit;
    }

    msg(MSG_NORMAL, "⦁ sd-boot: Updating (%s) kernel package : %s %s\n", conf->oper_str, info->package, info->vers);

    if (!is_kernel_sd_boot_managed(pkgs_arr, info)) {
        msg(MSG_NORMAL, "  not managed by sd-boot - skipping %s\n", info->package);
        goto exit;
    }

    /*
     * update file with curr/prev package versions
     */
    size_t len = sizeof(pkg_vers.current);
    if (strlcpy(pkg_vers.current, info->vers, len) > len) {
        ret = 1;
        goto exit;
    }

    ret = update_package_versions(conf, info->package, &pkg_vers);
    if (ret != 0) {
        goto exit;
    }
    curr = info->vers;
    prev = pkg_vers.previous;

    /*
     * If adding new version, remove previous
     */
    if (conf->oper == KI_ADD) {
        ret = remove_prev_version(conf, prev, curr);
        if (ret != 0) {
            goto exit;
        }
    }

    /*
     * Install the new version
     * - set up argv, envp
     * - env includes KERNEL_INSTALL_PLUGINS
     */
    ret = init_arg_env(conf, info, &arg_arr, &env_ptr);
    if (ret != 0) {
        goto exit;
    }

    /*
     * env variables:
     *  add => KERNEL_INSTALL_PLUGINS (empty if not testing)
     *  remove => empty 
     * Note that PATH, BOOT_ROOT are handled in kernel_install_run).
     */
    ret = kernel_install_run(conf, &arg_arr, env_ptr);
    if (ret != 0) {
        msg(MSG_ERR, "  ! sd-boot: error installing kernel\n");
        ret = 1;
        goto exit;
    }
    msg(MSG_NORMAL, "  ↳ sd-boot: Completed kernel update %s\n", info->package);

exit:
    array_str_free(&arg_arr);
    return ret;
}

