// SPDX-License-Identifier: GPL-2.0-or-later
// SPDX-FileCopyrightText: © 2026-present Gene C <arch@sapience.com>
/**
 *
 * Install or remove kernel using kernel-install.
 *
 *
 * /usr/lib/module/<kern-vers>/ ==> "$boot_root"/<machine-id>/
 * initrd is generated by kernel-install.
 *
 * See man kernel-install for "boot_root"
 */
#include <stdbool.h>
#include <stddef.h>
#include <string.h>

#include "sd-boot.h"
#include "sd-boot-config.h"
#include "sd-boot-kernel.h"
#include "sd-boot-msg.h"
#include "sd-boot-utils.h"


/**
  * inspect one kernel package
  */
int kernel_inspect(SdBoot *conf, Array_str *pkgs_arr, KernelInfo *info) {
    int ret = 0;
    Array_str arg_arr = {};
    Array_str env_arr = {};

    if (!info->vers || info->vers[0] == '\0') {
        msg(MSG_ERR, "  ! sd-boot: kernel update failed to get kernel version\n");
        ret = 1;
        goto exit;
    }

    msg(MSG_NORMAL, "⦁ sd-boot: inspecting (%s) kernel package : %s %s\n", conf->oper_str, info->package, info->vers);

    if (!is_kernel_sd_boot_managed(pkgs_arr, info)) {
        msg(MSG_NORMAL, "  not managed by sd-boot - skipping %s\n", info->package);
        goto exit;
    }

    /*
     * inspect the (current) version
     */
    ret = array_str_new(3, &arg_arr);
    if (ret != 0) {
        goto exit;
    }

    arg_arr.rows[0] = strdup("inspect");
    arg_arr.rows[1] = strdup(info->vers);
    arg_arr.rows[2] = strdup(info->image);

    if (!arg_arr.rows[0] || !arg_arr.rows[1] || !arg_arr.rows[2]) {
        ret = -1;
        goto exit;
    }

    /*
     * env provided by us:
     *  KERNEL_INSTALL_PLUGINS (empty if not testing)
     */

    ret = kernel_install_run(conf, &arg_arr, &conf->env_active_plugins);
    if (ret != 0) {
        msg(MSG_ERR, "  ! sd-boot: error inspecting kernel\n");
        ret = 1;
        goto exit;
    }
    msg(MSG_NORMAL, "  ↳ sd-boot: Completed kernel inspect %s\n", info->package);

exit:
    array_str_free(&arg_arr);
    array_str_free(&env_arr);
    return ret;
}

