// SPDX-License-Identifier: GPL-2.0-or-later
// SPDX-FileCopyrightText: © 2026-present Gene C <arch@sapience.com>
/**
 *
 * Install or remove kernel using kernel-install.
 *
 *
 * /usr/lib/module/<kern-vers>/ ==> "$boot_root"/<machine-id>/
 * initrd is generated by kernel-install.
 *
 * See man kernel-install for "boot_root"
 */
#include <linux/limits.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "sd-boot.h"

/*
 * Check if kernel vers exists by checking /usr/lib/modules/<vers>/vmlinuz
 * Informational only so don't fail.
 */
static bool does_kernel_version_exist(const char *kernel_version) {
    char path[PATH_MAX] = {};

    if (snprintf(path, PATH_MAX, "/usr/lib/modules/%s/vmlinuz", kernel_version) < 0) {
        return false;
    }

    if (access(path, F_OK) == 0) {
        return true;
    }

    return false;
}

/**
  * Update one kernel package
  * - oper ~ add or remove
  */
int kernel_add_remove(SdBoot *conf, Array_str *pkgs_arr, KernelInfo *info) {
    int ret = 0;
    char *curr = nullptr;
    char *prev = nullptr;
    char **envp = nullptr;
    PackageVersion pkg_vers = {};
    Array_str env = {};

    if (!info->vers || info->vers[0] == '\0') {
        msg(MSG_ERR, "  ! sd-boot: kernel update failed to get kernel version\n");
        ret = 1;
        goto exit;
    }

    msg(MSG_NORMAL, "⦁ sd-boot: Updating (%s) kernel package : %s %s\n", conf->oper_str, info->package, info->vers);

    if (!is_kernel_sd_boot_managed(pkgs_arr, info)) {
        msg(MSG_NORMAL, "  not managed by sd-boot - skipping %s\n", info->package);
        goto exit;
    }

    /*
     * update file with curr/prev package versions
     */
    size_t len = sizeof(pkg_vers.current);
    if (strlcpy(pkg_vers.current, info->vers, len) > len) {
        ret = 1;
        goto exit;
    }

    ret = update_package_versions(conf, info->package, &pkg_vers);
    if (ret != 0) {
        goto exit;
    }
    curr = info->vers;
    prev = pkg_vers.previous;

    /*
     * remove prev version 
     * - skip on update where prev = curr
     * - version string is = "<package>-<prev>"
     *   i.e. augment version string with package name
     * - an alpm remove hook may have been run. 
     *   check if the kernel image exists and display message.
     *   Still call kernel-install remove in case it has any housekeeping
     *   or other tasks to do.
     */
    if (conf->oper == KI_ADD && prev[0] != '\0' && strcmp(curr, prev) != 0) {
        msg(MSG_NORMAL, "  ↳ sd-boot: removing prev version %s\n", prev);

        if (!does_kernel_version_exist(prev)) {
            msg(MSG_NORMAL, "           : prev version already removed\n");
        }

        char *cmd_args[] = {"remove", prev, nullptr};

        ret = kernel_install_run(conf, cmd_args, nullptr);
        if (ret != 0) {
            msg(MSG_ERR, "  ! sd-boot: error removing prev kernel %s\n", prev);
            ret = 1;
            goto exit;
        }
    }

    /*
     * Install the new (current) version
     */
    const char *cmd_args_add[] = {"add", info->vers, info->image, nullptr};
    const char *cmd_args_remove[] = {"remove", info->vers, nullptr};
    char **cmd_args = nullptr;

    switch (conf->oper) {
        case KI_REMOVE:
            cmd_args = (char **)cmd_args_remove;
            break;

        case KI_ADD:
            cmd_args = (char **)cmd_args_add;
            break;

        default:
            goto exit;
    }
    /*
     * env provided by us:
     *  PATH
     *  KERNEL_INSTALL_PLUGINS (empty if not testing)
     *  (Note that BOOT_ROOT is handled in kernel_install_run).
     */
    ret = ki_kernel_update_env(conf, &env);
    if (ret != 0) {
        return ret;
    }
    envp = env.rows;

    ret = kernel_install_run(conf, cmd_args, envp);
    if (ret != 0) {
        msg(MSG_ERR, "  ! sd-boot: error installing kernel\n");
        ret = 1;
        goto exit;
    }
    msg(MSG_NORMAL, "  ↳ sd-boot: Completed kernel update %s\n", info->package);

exit:
    array_str_free(&env);
    return ret;
}

