// SPDX-License-Identifier: GPL-2.0-or-later
// SPDX-FileCopyrightText: © 2026-present Gene C <arch@sapience.com>
/**
 *
 * Install or remove kernel using kernel-install.
 *
 *
 * /usr/lib/module/<kern-vers>/ ==> "$boot_root"/<machine-id>/
 * initrd is generated by kernel-install.
 *
 * See man kernel-install for "boot_root"
 */
#include <string.h>

#include "sd-boot-config.h"
#include "sd-boot-kernel.h"
#include "sd-boot-msg.h"
#include "sd-boot-utils.h"
#include "sd-boot.h"

/*
 * Prep args and env.
 * For add we use env_plugins already initialized.
 * For remove we use empty env.
 */
static int init_arg_arr(SdBoot *conf, PkgInfo *info, Array_str *arg_arr) {

    int ret = 0;

    switch (conf->oper) {
        case KI_REMOVE:

            ret = array_str_new(2, arg_arr);
            if (ret != 0) {
                goto exit;
            }

            arg_arr->rows[0] = strdup(conf->oper_str);
            arg_arr->rows[1] = strdup(info->ki_vers);

            if (!arg_arr->rows[0] || !arg_arr->rows[1]) {
                ret = -1;
                goto exit;
            }
            break;

        case KI_ADD:
        case KI_INSPECT:

            ret = array_str_new(3, arg_arr);
            if (ret != 0) {
                goto exit;
            }

            arg_arr->rows[0] = strdup(conf->oper_str);
            arg_arr->rows[1] = strdup(info->ki_vers);
            arg_arr->rows[2] = strdup(info->ki_image);

            if (!arg_arr->rows[0] || !arg_arr->rows[1] || !arg_arr->rows[2]) {
                ret = -1;
                goto exit;
            }
            break;

        default:
            goto exit;
    }

    array_str_refresh_row_len(arg_arr);

exit:
    return ret;
}

/**
  * Update one kernel
  * - oper ~ add, inspect or remove
  */
int kernel_update_one(SdBoot *conf, PkgInfo *info) {
    int ret = 0;
    Array_str arg_arr = {};
    Array_str *env_ptr = nullptr;

    if (!info) {
        msg(MSG_ERR, "  ! sd-boot: kernel update bad input\n");
        ret = 1;
        goto exit;
    }

    if (!info->managed) {
        msg(MSG_NORMAL, "  not managed by sd-boot - skipping %s\n", info->pkg_name);
        goto exit;
    }

    msg(MSG_NORMAL, "⦁ sd-boot: Updating (%s) kernel package : %s %s\n", 
            conf->oper_str, info->pkg_name, info->pkg_vers);

    /*
     * Install the new version
     * - set up argv, envp
     * - env includes KERNEL_INSTALL_PLUGINS
     */
    env_ptr = &conf->env_active_plugins;
    ret = init_arg_arr(conf, info, &arg_arr);
    if (ret != 0) {
        goto exit;
    }

    /*
     * env variables:
     *  add => KERNEL_INSTALL_PLUGINS (empty if not testing)
     *  remove => empty 
     * Note that PATH, BOOT_ROOT are handled in kernel_install_run).
     */
    ret = kernel_install_run(conf, &arg_arr, env_ptr);
    if (ret != 0) {
        msg(MSG_ERR, "  ! sd-boot: error %s kernel\n", conf->oper_str);
        ret = 1;
        goto exit;
    }
    msg(MSG_NORMAL, "  ↳ sd-boot: Completed kernel update %s\n", info->pkg_name);

exit:
    array_str_free(&arg_arr);
    return ret;
}

