#!/usr/bin/bash
#
# Set up the test directory.
#
# Since meson runs tests in parallel we need bit of care
# to only set up the testing tree once.
#
# Arguments:
#  $1 = source directory
#  $2 = build directory
#  $3 = [valgrind] prog args
#

cwd=$(/usr/bin/pwd)
source_dir="$1"
build_dir="$2"
shift 2

testing_dir="$source_dir/tests/Testing"

#
# parent pid (meson) to ensure each meson test run installs once.
# meson runs multiple tests at same time. 
#
ppid="$PPID"
lock_file="$build_dir/.init_test.lock"
install_done_file="$build_dir/.init_install_done.$ppid"
{
    echo "sd-boot: initilizing test setup."
    # exclusive lock
    flock -x 9

    # if this meson test run is not setup then do it.
    if [[ ! -f "$install_done_file" ]] ; then
        /usr/bin/mkdir -p "$testing_dir/__root__"
        /usr/bin/rsync -a "$testing_dir"/Template/__root__ "$testing_dir/"

        cd "$source_dir"
        /usr/bin/meson install -C build/release --destdir "$testing_dir"/__root__ --quiet

        # remove any old (stale) install files and set up new one
        /usr/bin/rm -f "$build_dir"/.init_install_done.*
        touch "$install_done_file"

        # make sure linux is listed as packaage handled by sd-boot (for testing)
        echo "linux" >> "$testing_dir/__root__/etc/sd-boot/kernel.packages"
        cd $cwd
    fi
} 9>"$lock_file"

#
# Call Run script passed in: run-one-test [valgrind] <prog> <input-file> [args]
#

if [[ "$1" == "valgrind" ]] ; then
    shift 1
    prog="$1"
    shift 1
    prog="$prog valgrind"
else
    prog="$1"
    shift 1
fi
echo "  Running test $1"
exec $prog "$@"

exit 0

