#!/usr/bin/bash
#
# Run test suite
# - run from the "src" directory
# 
# Tools called via ALPM hooks read triggers from stdin. 
# Input data for these is in Triggers/
# In gdb run using:  run add < Triggers/xxx
#
# Note the kernel used for testing is the arch kernel 
# Arch kernel is not managed by sd-boot by default.
# See: /etc/sd-boot/kernel.packages
# The test tree is created from he template tree : Testing/template
# To test other kernels, add them to file: 
#     Testing/template/__root__/etc/sd-boot/kernels.packages
#

echo "sd-boot test suite."
cwd=$(/usr/bin/pwd)

/usr/bin/meson setup --reconfigure build/release --buildtype=release -Ddefault_library=shared
/usr/bin/meson compile -C build/release

echo ""
echo "-----------------------------"
echo " Standard:"
echo "------------"
echo ""
/usr/bin/meson test -C build/release --setup=standard

echo ""
echo "-----------------------------"
echo " Valgrind:"
echo "------------"
echo ""
/usr/bin/meson test -C build/release --setup=valgrind

exit 0

