#!/usr/bin/bash
#
# Static checks.
# Must be run in src dir.
# - cppcheck
# - clang-tidy
# 
echo "-----------------------------"
echo " Static checks:"
echo "-----------------------------"

src_dir=$(/usr/bin/pwd)
log_dir="$src_dir/tests/Logs"
/usr/bin/mkdir -p "$log_dir"

echo ""
echo " Logs are in $log_dir"
echo ""

echo " cppcheck:"

libs=(lib lib-efi lib-kernel)
tools=(tools tools-efi tools-kernel tools-plugins)
/usr/bin/cppcheck "${libs[@]}" "${tools[@]}"   2>&1 > "$log_dir/cppcheck"

echo " clang-tidy:"

# ensure compile_commands.json is available
meson setup --reconfigure build/release --buildtype=release -Ddefault_library=static  > /dev/null

shopt -s nullglob
c_files=()
for i in "${libs[@]}" "${tools[@]}"
do
    c_files+=("$i"/*.c)
done
/usr/bin/clang-tidy -p build/release "${c_files[@]}" > "$log_dir/clang-tidy" 2>&1

