// SPDX-License-Identifier: GPL-2.0-or-later
// SPDX-FileCopyrightText: © 2026-present Gene C <arch@sapience.com>
/**
 *
 * Install or remove kernel using kernel-install.
 * Invoked by pacman alpm hook along with "triggers" on stdin.
 *
 * /usr/lib/module/<kern-vers>/ ==> "$boot_root"/<machine-id>/
 * initrd is generated by kernel-install.
 *
 * See man kernel-install for "boot_root"
 */
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "sd-boot-config.h"
#include "sd-boot-kernel.h"
#include "sd-boot-msg.h"
#include "sd-boot-utils.h"

struct Work {
    SdBoot conf;
    const char *pkg;
    Triggers trigs;
    Array_str pkgs_arr;
};

void work_clean(struct Work *work) {
    config_clean(&work->conf);
    free_triggers(&work->trigs);
    array_str_free(&work->pkgs_arr);
}

/*
 * Check if kernel already done from a kernel image (specific) trigger
 */
static bool this_kernel_already_done(KernelInfo *info, Triggers *trigs) {
    bool done = false;

    if (!info->package || info->package[0] == '\0') {
        return done;
    }

    for (size_t i = 0; i < trigs->num_info; i++) {
        if (!trigs->info[i].package || trigs->info[i].package[0] == '\0') {
            continue;
        }

        if (strcmp(info->package, trigs->info[i].package) == 0) {
            done = true;
            break;
        }
    }
    return done;
}

/**
 * - Check arguments.
 * - load config
 * - read trigger list
 * Input:
 *      argc, argv
 * Returns:
 *      oper  = add or remove
 *      conf  = config file data
 *      trigs = Triggers data read from stdin
 */
static int initialize(int argc, char *argv[], struct Work *work) {
    int ret = 0;
    const char *self = "kernel-update-triggers";

    if (argc < 2) {
        msg(MSG_ERR, "! sd-boot: %s missing add or remove\n", self);
        ret = 1;
        goto exit;
    }
    const char *oper_str = argv[1];

    work->conf.oper = KI_BAD;
    work->conf.oper = kernel_install_oper(oper_str);
    work->conf.oper_str = strdup(argv[1]);

    if (work->conf.oper == KI_BAD) {
        msg(MSG_ERR, "! sd-boot: %s expect add or remove but got %s\n", self, work->conf.oper_str);
        ret = 1;
        goto exit;
    }

    if (load_config(&work->conf) != 0) {
        msg(MSG_VERB, "- sd-boot: %s warning failed to load config config file\n", self);
    }

    /*
     * triggers
     */
    ret = get_kernel_triggers(&work->trigs);
    if (ret != 0) {
        msg(MSG_ERR, "  ! sd-boot error reading kernel triggers\n");
        ret = 1;
        goto exit;
    }

    /*
     * kernels managed by sd-boot
     */
    ret = load_managed_kernel_packages(&work->conf, &work->pkgs_arr);

exit:
    return ret;
}

/**
 * Takes one argument:
 * - add or remove
 *
 * - add:
 *   - Install or update kernel into boot_root
 *
 * - remove
 *   - remove kernel files from boot_root
 * Triggers:
 *      a) /usr/lib/modules/<kenr-vers>/vmlinux
 *      b) non-kernel paths
 *      c) any packages which impact initrd or uki image.
 *
 * Required Files:
 *  a) /etc/sd-boot/kernel-install.packages
 *     List of kernel packages managed by sd-boot
 *  b) /usr/lib/modules/<kern-vers>/<pkgbase>
 *
 *    This file provides the package name of that kernel.
 *    <pkgbase> file will be looked for in order:
 *      gc-pkgbase pkgbase-sdb or pkgbase
 */
int main(int argc, char *argv[]) {
    int ret = 0;
    struct Work work = {};
    size_t num_all = 0;
    KernelInfo *infos = nullptr;

    ret = initialize(argc, argv, &work);
    if (ret != 0) {
        goto exit;
    }

    /*
     * Process Triggers:
     * 1) kernel specific triggers (/usr/lib/modules/<kvers>/vmlinuz
     *    install the specific kernel 
     *
     * 2) other triggers (path or package)
     *    update every kernel if operation is "add"
     * 
     * Kernels are updated only if they are in the list of 
     * kernel packages managed by sd-boot.
     *
     * Do any kernel once only, regardless of number of triggers.
     */

    /*
     * kernel specific triggers
     * ------------------------
     * - applies to a specific kernel.
     * - kernel trigger ~ /usr/lib/modules/<kern-vers>/vmlinuz
     *   => kernel package name
     * - number of non-kernel triggers = any other triggers (apply to every kernel).
     */
    for (size_t i = 0; i < work.trigs.num_info; i++) {
        if (!is_kernel_sd_boot_managed(&work.pkgs_arr, &work.trigs.info[i])) {
            continue;
        }

        ret = kernel_add_remove(&work.conf, &work.pkgs_arr, &work.trigs.info[i]);
        if (ret != 0) {
            goto exit;
        }
    }

    /*
     * other kernel triggers
     * ---------------------
     * - applies to all kernels.
     * - NB only applicable for "add" not remove
     *   remove must be for specific kernel.
     * - Create a list of kernels not already updated above.
     */
    if (work.trigs.num_other > 0 && work.conf.oper == KI_ADD) {
        /*
         * Gather kernel info
         */
        ret = kernel_info_all(&num_all, &infos);
        if (ret != 0) {
            ret = 1;
            goto exit;
        }

        for (size_t i = 0; i < num_all; i++) {
            if (this_kernel_already_done(&infos[i], &work.trigs)) {
                continue;
            }

            ret = kernel_add_remove(&work.conf, &work.pkgs_arr, &infos[i]);
            if (ret != 0) {
                goto exit;
            }
        }
    }

exit:
    work_clean(&work);
    if (infos) {
        for (size_t i = 0; i < num_all; i++) {
            kernel_info_free(&infos[i]);
        }
        free((void *)infos);
    }
    return ret;
}

