// SPDX-License-Identifier: GPL-2.0-or-later
// SPDX-FileCopyrightText: © 2026-present Gene C <arch@sapience.com>
/**
 *
 * Install or remove kernel using kernel-install.
 * Invoked by pacman alpm hook along with "triggers" on stdin.
 *
 * /usr/lib/module/<kern-vers>/ ==> "$boot_root"/<machine-id>/
 * initrd is generated by kernel-install.
 *
 * Similar to sd-boot-kernel-update except triggers are read from stdin
 * instead of a package name on the command line.
 *
 * See man kernel-install for "boot_root"
 */
#include <stdbool.h>

#include "sd-boot.h"
#include "sd-boot-config.h"
#include "sd-boot-kernel.h"
#include "sd-boot-msg.h"
#include "sd-boot-tool.h"

static bool operation_supported(Operation oper) {

    switch (oper) {
        case KI_ADD:
        case KI_REMOVE:
            return true;
            break;

        default:
            return false;
            break;
    }
}

static int initialize(int argc, char *argv[], Tool *tool) {
    int ret = 0;

    tool->triggers = true;

    ret = initialize_tool(SDB_KERNEL, 2, argc, argv, tool);
    if (ret != 0) {
        msg(MSG_ERR, "!  sd-boot: kernel-update-triggers failed to initialize\n");
        ret = 1;
        goto exit;
    }

    if (!operation_supported(tool->conf.oper)) {
        msg(MSG_ERR, "  ! sd-boot: unsupported opertion: %s\n", tool->conf.oper_str);
        ret = 1;
        goto exit;
    }

exit:
    return ret;
}

/**
 * Takes one argument:
 * - add or remove
 *
 * - add:
 *   - Install or update kernel into boot_root
 *
 * - remove
 *   - remove kernel files from boot_root
 *
 * Triggers:
 * - Provided by pacman from alpm hoooks and are read from stdin
 *
 *  b) /usr/lib/modules/<kern-vers>/<pkgbase>
 *
 *    This file provides the package name of that kernel.
 *    <pkgbase> file will be looked for in order:
 *      gc-pkgbase pkgbase-sdb or pkgbase
 */
int main(int argc, char *argv[]) {
    int ret = 0;
    Tool tool = {};

    ret = initialize(argc, argv, &tool);
    if (ret != 0) {
        goto exit;
    }

    /*
     * True if any pkginfo packages are managed by us.
     */
    if (!tool.managed) {
        goto exit;
    }

    /*
     * Do it
     */
    ret = kernel_update_execute(&tool);
    if (ret != 0) {
        ret = 1;
        goto exit;
    }

exit:
    tool_free(&tool);
    return ret;
}

