#!/usr/bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later 
# Copy the EFI filesytem drivers to <esp>/EFI/systemd/drivers/
#
# 1 Argument Required : must be 'add' or 'remove'
#
# EFI mount point is located by calling sd-boot-find-efi.
# 
set -e

#
# Operation
#
if [[ -z "$1" ]]; then
    echo "sd-boot-efi-tool-update: missing add/remove argument"
    exit 0
fi

case "$1" in
    "install" | "add")
        oper="add"
        ;;
     "remove")
         oper="remove"
         ;;
     *)
         echo "sd-boot-efi-tool-update: bad option $oper"
         exit 0
esac

#
# locate efi 
#
efi=$(/usr/lib/sd-boot/sd-boot-find-efi)

if [[ -z "$efi" ]] ; then
    echo "sd-boot: failed to find EFI mount"
    exit 0
fi

if [[ ! -d "$efi" ]]; then
    echo "sd-boot:  EFI dir $efi not a directory"
    exit
fi

case "$oper" in
    "add")
        # shellcheck disable=SC1091
        echo "sd-boot Copying efi filesystem drivers to: $efi"
        /usr/bin/rsync --mkpath -a /usr/lib/efifs-x64/ "$efi"/EFI/systemd/drivers/
        ;;
        

    "remove")
        echo "sd-boot Removing efi filesystem drivers from: $efi"
        /usr/bin/rm -rf "$efi"/EFI/systemd/drivers
        ;;
esac
