#!/usr/bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later 
# Install or remove bootable efi programs (e.g. efi-shell) from EFI partition.
#
# Called from alpm-hooks:
#   99-sd-boot-efi-tool-install.hook    - install/upgrade
#   69-sd-boot-efi-tool-remove.hook     - remove
# 
# Usage:
#   sd-boot-efi-shell-update add|remove
# 
#
set -e

#
# Operation
#
if [[ -z "$1" ]]; then
    echo "sd-boot-efi-tool-update: missing add/remove argument"
    exit 0
fi

case "$1" in
    "install" | "add") 
        oper="add" 
        ;;
     "remove") 
         oper="remove" 
         ;;
     *) 
         echo "sd-boot-efi-tool-update: bad option $oper"
         exit 0
esac

#
# Load support functions
#
function_dir="/usr/lib/sd-boot/functions"

# shellcheck source=./lib/functions/load-config.sh
source "$function_dir/load-config.sh"

declare -A config
sd_boot_load_config config

if [[ -v config["verb"] ]]; then
    verb="${config[verb]}"
else
    verb=0
fi

# shellcheck source=./lib/functions/load-efi-image_file.sh
source "$function_dir/load-efi-image_file.sh"

# shellcheck source=./lib/functions/load-package-version.sh
source "$function_dir/load-package-version.sh"

#
# Read Triggers (must be package names)
#

#
# Over-ride the plugins that are run - it is bootable efi tool not a kernel.
# We want efi image installed and a loader-entry (nothing else)
# Uses KERNEL_INSTALL_PLUGINS env variable (see man kernel-install)
#
sys_dir="/usr/lib/kernel/install.d"
etc_dir="/etc/kernel/install.d"
sys_plugins=( 90-loaderentry.install )
etc_plugins=( 95-sd-boot-loaderentry-efi.install ) 

KERNEL_INSTALL_PLUGINS=""
for plugin in "${sys_plugins[@]}"
do
    KERNEL_INSTALL_PLUGINS="$KERNEL_INSTALL_PLUGINS $sys_dir/$plugin"
done
for plugin in "${etc_plugins[@]}"
do
    KERNEL_INSTALL_PLUGINS="$KERNEL_INSTALL_PLUGINS $etc_dir/$plugin"
done
export KERNEL_INSTALL_PLUGINS

#
# Each trigger is package name which must appear only once - duplicates 
# can mess up the file holding current / previous version.
#
while read -r pkg
do
    if (( verb > 1)) ; then
        echo "  sd-boot-efi-tool-update change package trigger: $pkg"
    fi
    case "$oper" in
        "add")
            #
            # Saves the version and previous version of target package to file
            #  /var/lib/sd-boot/<package>.version
            #  We dont have the new version so it will use pacman -Q to find it.
            #
            /usr/lib/sd-boot/sd-boot-package-version-update add "$pkg"

            #
            # Read back package versions and the efi image file to install to EFI
            # - the versions we just updated so curr_version is the new just updated/installed one.
            prev_vers=''
            curr_vers=''
            efi_image=''
            sd_boot_load_package_versions "$pkg" curr_vers prev_vers
            sd_boot_load_efi_image_file "$pkg" efi_image

            # current version of this package
            if [[ -z "$curr_vers" || -z "$efi_image" ]] ; then
                echo "sd-boot-efi-tool-update: failed to get version or efi_image for: $pkg"
                continue
            fi

            # for kernel-intall we augment the package version with the package name
            version="$pkg-$curr_vers"
            prev_version=''
            if [[ "$prev_vers" != "" ]] ; then
                prev_version="$pkg-$prev_vers"
            fi

            #
            # Have version and efi image path -> add/remove this from EFI
            #
            if (( verb > 1 )) ; then
                echo "    sd-boot-efi-tool-update: kernel-install" "$oper" "${curr_vers}"
            fi

            # -------------------------------
            echo "sd-boot: Updating tool to efi: $pkg $curr_vers"
            if [[ ! -z "$prev_version" && "$prev_version" != "$version" ]] ; then
                #
                # Remove the previous version
                # re-install : safe to kernel-install remove <vers> multiple times
                #
                if (( verb > 0)) ; then
                    echo "    sd-boot efi-tool: Removing previous version $prev_version"
                fi
                /usr/bin/kernel-install remove "$prev_version"
            fi
            /usr/bin/kernel-install add "$version" "$efi_image"
            ;;

        "remove")
            echo "sd-boot: Removing efi-shell from EFI : $pkg $version"
            /usr/bin/kernel-install remove "$version"
            /usr/lib/sd-boot/sd-boot-package-version-update remove "$pkg"
            ;;
    esac
done
    
exit 0
