#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later 
# Copy the EFI filesytem drivers to <esp>/EFI/systemd/drivers/
#
# 1 Argument Required : must be 'add' or 'remove'
#
# EFI mount point is located by calling sd-boot-find-efi.
# 
oper="$1"
if [[ -z "$oper" || "$oper" != "add" || "$oper" != "remove" ]] ; then
    echo "sd-boot-efifs-update: missing add/remove argument"
    exit 0
fi

#
# locate efi 
#
efi=$(/usr/lib/sd-boot/sd-boot-find-efi)

if [[ -z "$efi" ]] ; then
    echo "sd-boot: failed to find EFI mount"
    exit 0
fi

if [[ ! -d "$efi" ]]; then
    echo "sd-boot:  EFI dir $efi not a directory"
    exit
fi

case "$oper" in
    "add")
        # shellcheck disable=SC1091
        echo "sd-boot Copying efi filesystem drivers to: $efi"
        /usr/bin/rsync --mkpath -a /usr/lib/efifs-x64/ "$efi"/EFI/systemd/drivers/
        ;;
        

    "remove")
        echo "sd-boot Removing efi filesystem drivers from: $efi"
        /usr/bin/rm -rf "$efi"/EFI/systemd/drivers
        ;;
esac
