#!/usr/bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later 
# Find where ESP is for current boot is mounted. 
# NB each disk may have and ESP partition - this finds the one on the current booted disk.
#

efi=$(/usr/bin/bootctl 2>/dev/null | /usr/bin/grep -A1 'Available Boot Loaders on ESP:' \
    | /usr/bin/tail -1 | sed 's/^[[:blank:]]*//' | cut -d' ' -f 2)

xbootldr=$(/usr/bin/bootctl 2>/dev/null | /usr/bin/grep 'XBOOTLDR: ' \
    | /usr/bin/tail -1 | sed 's/^[[:blank:]]*//' | cut -d' ' -f 2)

if [[ "$1" == "" ]] ; then
    echo "efi     : $efi"
    echo "xbootldr: $xbootldr"
elif [[ "$1" == "xbootldr" ]] ; then
    echo "$xbootldr"
else
    echo "$efi"
fi
exit 0
