#
# loader.conf
# (/efi/loader/loader.conf)
# console-mode 2 needed for hi res screens (not auto)
# My stable kernel packaed is linux-stable - adjust as needed.
# *-stable* catches legacy and new kernel-install entries
# *-stable-* catches new kernel-install auto entries only
#
default *-stable*
timeout 5
editor  yes
console-mode auto
#console-mode 2

