#
# sd-boot: lib-config
#

#
# Source code
#
inc_dir += include_directories('.')

lib_sources += files(
    'config.c',
    'config_clean.c',
    'config_files.c',
    'config_init.c',
    'config_test.c',
    'env_base.c',
    'ki_install_conf.c',
    'ki_oper.c',
    'load_config_cyaml.c',
    'load_kernel_install.c',
    'read_kernel_install_files.c',
    )
