// SPDX-License-Identifier: GPL-2.0-or-later
// SPDX-FileCopyrightText: © 2026-present Gene C <arch@sapience.com>
/**
 *
 * Install or remove kernel using kernel-install.
 *
 *
 * /usr/lib/module/<kern-vers>/ ==> "$boot_root"/<machine-id>/
 * initrd is generated by kernel-install.
 *
 * See man kernel-install for "boot_root"
 */
#include <linux/limits.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "sd-boot.h"

/**
 * Check if kernel managed by sd-boot
 */
static bool is_sd_boot_managed(Array_str *pkgs_arr, KernelInfo *info) {
    bool good_kernel = false;

    if (info == nullptr || info->package == nullptr || info->package[0] == '\0') {
        goto exit;
    }
    for (size_t i = 0; i < pkgs_arr->num_rows; i++) {
        if (strcmp(info->package, pkgs_arr->rows[i]) == 0) {
            good_kernel = true;
            break;
        }
    }
exit:
    return good_kernel;
}

/*
 * Check if kernel vers exists by checking /usr/lib/modules/<vers>/vmlinuz
 * Informational only so don't fail.
 */
static bool does_kernel_version_exist(const char *kernel_version) {
    char path[PATH_MAX] = {'\0'};

    if (snprintf(path, PATH_MAX, "/usr/lib/modules/%s/vmlinuz", kernel_version) < 0) {
        return false;
    }

    if (access(path, F_OK) == 0) {
        return true;
    }

    return false;
}

/**
  * Update one kernel package
  * - oper ~ add or remove
  */
static int kernel_update_one(SdBoot *conf, Array_str *pkgs_arr, int oper, KernelInfo *info) {
    int ret = 0;
    char *curr = nullptr;
    char *prev = nullptr;
    char **envp = nullptr;
    PackageVersion pkg_vers = {};

    if (info->vers == nullptr || info->vers[0] == '\0') {
        msg(MSG_ERR, "  sd-boot: kernel update failed to get kernel version\n");
        ret = 1;
        goto exit;
    }

    msg(MSG_NORMAL, "sd-boot: Updating kernel package %s %s\n", info->package, info->vers);

    if (!is_sd_boot_managed(pkgs_arr, info)) {
        msg(MSG_NORMAL, "  not managed by sd-boot - skipping %s\n", info->package);
        goto exit;
    }

    /*
     * update file with curr/prev package versions
     */
    size_t len = sizeof(pkg_vers.current);
    if (strlcpy(pkg_vers.current, info->vers, len) > len) {
        ret = 1;
        goto exit;
    }

    ret = update_package_versions(conf, info->package, &pkg_vers);
    if (ret != 0) {
        goto exit;
    }
    curr = info->vers;
    prev = pkg_vers.previous;

    /*
     * remove prev version 
     * - skip on update where prev = curr
     * - version string is = "<package>-<prev>"
     *   i.e. augment version string with package name
     * - an alpm remove hook may have been run. 
     *   check if the kernel image exists and display message.
     *   Still call kernel-install remove in case it has any housekeeping
     *   or other tasks to do.
     */
    if (oper == ADD && prev[0] != '\0' && strcmp(curr, prev) != 0) {
        msg(MSG_NORMAL, "  sd-boot: removing prev version %s\n", prev);

        if (!does_kernel_version_exist(prev)) {
            msg(MSG_NORMAL, "         : prev version already removed\n");
        }

        char *cmd_args[] = {"remove", prev, nullptr};

        ret = kernel_install_run(conf, cmd_args, nullptr);
        if (ret != 0) {
            msg(MSG_ERR, "  sd-boot: error removing prev kernel %s\n", prev);
            ret = 1;
            goto exit;
        }
    }

    /*
     * Install the new (current) version
     */
    char *oper_string = nullptr;
    if (oper == REMOVE) {
        oper_string = "remove";
    } else {
        oper_string = "add";
    }
    char *cmd_args[] = {oper_string, info->vers, info->image, nullptr};
    /*
     * env provided by us:
     *  PATH
     *  KERNEL_INSTALL_PLUGINS (empty if not testing)
     *  (Note that BOOT_ROOT is handled in kernel_install_run).
     */
    char **envp_plugins = conf->info.env_all_plugins.rows;
    size_t num_envp_plugins = 0;
    size_t num_envp = 2;

    if (envp_plugins != nullptr) {
        num_envp_plugins = count_envp_argv(envp_plugins);
        num_envp += num_envp_plugins;
    }

    envp = (char **)calloc(num_envp, sizeof(char *));
    if (envp == nullptr){
        msg(MSG_ERR, "sd-boot: mem allocation failed\n");
        ret = -1;
        goto exit;
    }
    for (size_t i = 0; i < num_envp_plugins; i++) {
        envp[i] = envp_plugins[i];
    }
    envp[num_envp - 2] = "PATH=/usr/bin";
    envp[num_envp - 1] = nullptr;

    ret = kernel_install_run(conf, cmd_args, envp);
    if (ret != 0) {
        msg(MSG_ERR, "sd-boot: error installing efi tool\n");
        ret = 1;
        goto exit;
    }
    msg(MSG_NORMAL, "  sd-boot: Completed kernel update %s\n", info->package);

exit:
    if (envp != nullptr) {
        free((void *)envp);
    }
    return ret;
}


/*
 * Check if kernel already done from a kernel image (specific) trigger
 */
static bool did_this_kernel(KernelInfo *info, Triggers *trigs) {
    bool done = false;

    for (size_t i = 0; i < trigs->num_info; i++) {
        if (strcmp(info->package, trigs->info[i].package) == 0) {
            done = true;
            break;
        }
    }
    return done;
}

/**
 * - Check arguments.
 * - load config
 * - read trigger list
 * Input:
 *      argc, argv
 * Returns:
 *      oper  = add or remove
 *      conf  = config file data
 *      trigs = Triggers data read from stdin
 */
static int initialize(int argc, char *argv[], int *oper, 
        SdBoot *conf, Triggers *trigs, Array_str *pkgs_arr) {
    /*
     * Command line & Config
     */
    int ret = 0;
    if (argc < 2) {
        msg(MSG_ERR, "sd-boot: missing add or remove\n");
        ret = 1;
        goto exit;
    }

    *oper = BAD;
    *oper = kernel_install_oper(argv[1]);
    if (*oper == BAD) {
        msg(MSG_ERR, "sd-boot: expect add or remove but got %s\n", argv[1]);
        ret = 1;
        goto exit;
    }

    if (load_config(conf) != 0) {
        msg(MSG_VERB, "sd-boot: warning - no config file loaded - skipping\n");
    }

    /*
     * triggers
     */
    ret = get_kernel_triggers(trigs);
    if (ret != 0) {
        msg(MSG_ERR, "sd-boot error reading kernel triggers\n");
        ret = 1;
        goto exit;
    }

    /*
     * kernels managed by sd-boot
     */
    ret = load_kernel_packages(conf, pkgs_arr);

exit:
    return ret;
}

/**
 * Takes one argument:
 * - add or remove
 *
 * - add:
 *   - Install or update kernel into boot_root
 *
 * - remove
 *   - remove kernel files from boot_root
 * Triggers:
 *      a) /usr/lib/modules/<kenr-vers>/vmlinux
 *      b) non-kernel paths
 *      c) any packages which impact initrd or uki image.
 *
 * Required Files:
 *  a) /etc/sd-boot/kernel-install.packages
 *     List of kernel packages managed by sd-boot
 *  b) /usr/lib/modules/<kern-vers>/<pkgbase>
 *
 *    This file provides the package name of that kernel.
 *    <pkgbase> file will be looked for in order:
 *      gc-pkgbase pkgbase-sdb or pkgbase
 */
int main(int argc, char *argv[]) {
    int ret = 0;
    int oper = BAD;
    SdBoot conf = {};
    Triggers trigs = {};
    Array_str pkgs_arr = {};
    size_t num_all = 0;
    KernelInfo *infos = nullptr;

    ret = initialize(argc, argv, &oper, &conf, &trigs, &pkgs_arr);
    if (ret != 0) {
        goto exit;
    }

    /*
     * Process Triggers:
     * 1) kernel specific triggers (/usr/lib/modules/<kvers>/vmlinuz
     *    install the specific kernel 
     *
     * 2) other triggers (path or package)
     *    update every kernel if operation is "add"
     * 
     * Kernels are updated only if they are in the list of 
     * kernel packages managed by sd-boot.
     *
     * Do any kernel once only, regardless of number of triggers.
     */

    /*
     * kernel specific triggers
     * ------------------------
     * - applies to a specific kernel.
     * - kernel trigger ~ /usr/lib/modules/<kern-vers>/vmlinuz
     *   => kernel package name
     * - number of non-kernel triggers = any other triggers (apply to every kernel).
     */
    for (size_t i = 0; i < trigs.num_info; i++) {
        if (!is_sd_boot_managed(&pkgs_arr, &trigs.info[i])) {
            continue;
        }

        ret = kernel_update_one(&conf, &pkgs_arr, oper, &trigs.info[i]);
        if (ret != 0) {
            goto exit;
        }
    }

    /*
     * other kernel triggers
     * ---------------------
     * - applies to all kernels.
     * - NB only applicable for "add" not remove
     *   remove must be for specific kernel.
     * - Create a list of kernels not already updated above.
     */
    if (trigs.num_other > 0 && oper == ADD) {
        /*
         * Gather kernel info
         */
        ret = kernel_info_all(&num_all, &infos);
        if (ret != 0) {
            ret = 1;
            goto exit;
        }

        for (size_t i = 0; i < num_all; i++) {
            if (did_this_kernel(&infos[i], &trigs)) {
                continue;
            }

            ret = kernel_update_one(&conf, &pkgs_arr, oper, &infos[i]);
            if (ret != 0) {
                goto exit;
            }
        }
    }

exit:
    clean_config(&conf);
    free_triggers(&trigs);
    if (infos != nullptr) {
        for (size_t i = 0; i < num_all; i++) {
            kernel_info_free(&infos[i]);
        }
        free((void *)infos);
    }
    array_str_free(&pkgs_arr);
    return ret;
}

